### ISSUE TITLE
"hermit" crate on crates.io

### ISSUE THREAD

**Issue by jounathaen** [snnsnn/electron-vite-solid#3]
Hi @snnsnn, 
Sorry, this is not about electron-vite-solid, but I don't know how to reach out to you elseway.
You own the crate `hermit` on crates.io, but it seems you are not using it. I'm one of the maintainers of the [rusty-hermit ](https://github.com/hermitcore/rusty-hermit) unikernel, and we'd be interested in using that crate name.
If you'd be interested, please reach out to me :slightly_smiling_face: .

Best,
Jonathan

**Comment by snnsnn** [comment]
@jounathaen Sorry, I forgot to write back,  I could not verify your maintainership position and trasferred the ownership to @stlankes who is the owner of the all hermit related crates. Hope you did not mind.

**Comment by jounathaen** [comment]
Perfect! He is sitting just a few offices away from me :grin: 
Thank you very much!

**Comment by snnsnn** [comment]
> Perfect! He is sitting just a few offices away from me 😁 Thank you very much!

Great, send my regards 👋👋. Happy to help.

**Comment by snnsnn** [comment]
@jounathaen By the way,  there is a very cool meta project, https://github.com/facebookexperimental/hermit, which some parts of it may overlap with your project too. Just to let you know in case if you did not know about. Someone from their team has emailed me for the namespace for  few monts ago but he did not provide a username, neither answered my email.

**Comment by jounathaen** [comment]
Very Interesting. Didn't know that one yet :thinking: Thank you for sharing.
